### ISSUE TITLE
OMP: Error #15: Initializing libiomp5md.dll

### ISSUE THREAD

**Issue by shaharsu** [idptools/metapredict#6]
Running on windows. When metapredict is imported together with matplotlib, an error is produced when any plotting function is called, and the kernel crashes and requires a restart:

```
OMP: Error #15: Initializing libiomp5md.dll, but found libiomp5md.dll already initialized.
OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.
```

The workaround I have is to run the following line before the script executes:

```
import os
os.environ["KMP_DUPLICATE_LIB_OK"]="TRUE"
```

it works fine, but probably other people will have this issue as well. it's very reproducible.

**Comment by ryanemenecker** [comment]
Hi Shaharsu - 
This is a known problem with metapredict. In our ReadMe.md, we have a section on how to deal with it

''
Known Installation/Execution Issues
Below we include documentation on known issues.

macOS libiomp clash

PyTorch current ships with its own version of the OpenMP library (libiomp.dylib). Unfortunately when numpy is installed from conda (although not from pip) this leads to a collision because the conda-derived numpy library also includes a local copy of the libiomp5.dylib library. This leads to the following error message (included here for google-ability).

OMP: Error #15: Initializing libiomp5.dylib, but found libomp.dylib already initialized. OMP: Hint This means that multiple copies of the OpenMP runtime have been linked into the program. That is dangerous, since it can degrade performance or cause incorrect results. The best thing to do is to ensure that only a single OpenMP runtime is linked into the process, e.g. by avoiding static linking of the OpenMP runtime in any library. As an unsafe, unsupported, undocumented workaround you can set the environment variable KMP_DUPLICATE_LIB_OK=TRUE to allow the program to continue to execute, but that may cause crashes or silently produce incorrect results. For more information, please see http://www.intel.com/software/products/support/.

To avoid this error we make the executive decision to ignore this clash. This has largely not appeared to have any deleterious issues on performance or accuracy across the tests run. If you are uncomfortable with this then the code in metapredict/__init__.py can be edited with IGNORE_LIBOMP_ERROR set to False and metapredict re-installed from the source directory.
''
It's basically a problem with conda installing numpy.

Thanks for raising the issue!

**Comment by RossLabCSU** [comment]
Just to clarify...for v2.51, this issue still occurs on Windows even when IGNORE_LIBOMP_ERROR=True in metapredict/init.py. I believe the reason is that init.py only sets the environment variable "if sys.platform == 'darwin':". If I just remove this "if" statement in init.py, metapredict runs without issue. Apologies if this has changed in v2.6 and higher: I'm still using v2.51 because I have been unable to install any version >2.51 on Windows with (at the time) up-to-date Anaconda.

**Comment by alexholehouse** [comment]
Ohhhhh this is a good point - thanks! We should probably catch `darwin` and `windows`here...
